version: '3.8'

services:
  postgres:
    image: postgres
    container_name: some-postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /custom/mount:/var/lib/postgresql/data

  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb-postgres
    ports:
      - "8080:8080"
    environment:
      - NC_DB=pg://postgres:5432?u=postgres&p=mysecretpassword&d=d1
      - NC_AUTH_JWT_SECRET=569a1821-0a93-45e8-87ab-eb857f20a010
    volumes:
      - ./nocodb:/usr/app/data
    depends_on:
      - postgres
